### ISSUE TITLE
[Feature Request] Continuos Training

### ISSUE THREAD

**Issue by khursani8** [matteo-39/vosk-build-model#1]
Hi, thanks for creating this guide, it really useful for me who don't understand much about bash scripting. I managed to create the model with wav and txt file only. 

Can you create a guide for fine tuning the model or lifelong learning(https://github.com/alphacep/vosk/blob/master/index.py)?

thanks

**Comment by matteo-convertino** [comment]
Hi, regarding fine tuning I have searched a bit and I would suggest you these link: https://github.com/kaldi-asr/kaldi/issues/2374, https://github.com/daanzu/kaldi-active-grammar/issues/33.
I'm really sorry but I can't optimize the code, test it and write all in a guide, it would take me too long and in this moment I am working in another project.

Instead, about lifelong learning, that project is not what are you looking for?

**Comment by khursani8** [comment]
Hi, thanks for the link, I will take a look at it

As for lifelong learning, I don't understand how to integrate it will the trained kaldi model(probably it is a separate thing) and to me it kind of abandoned since last update is 2 years ago.

Thanks
